### ISSUE TITLE
Instructions don't (seem?) to work for me

### ISSUE THREAD

**Issue by thewhitegrizzli** [djarosz/vsftpd#2]
I think it has something to do with the part about generating the credentials (tom/foo) DB using db_load3.

I have retried multiple times without success.

Using VSFTPD 3.0.3

I get a 530 error on login attempt.

Any ideas?

**Comment by djarosz** [comment]
@thewhitegrizzli This issue should be rather asked to orignal vsftpd developer. As this is just old fork for patch I needed and instructions given in INSTALL taken from upsteram project (https://security.appspot.com/vsftpd.html#about). As far as I know vftpsd author did not release source code on github

**Comment by thewhitegrizzli** [comment]
Correct. Thank you very much and sorry for the hassle.
